apiVersion: v1
kind: Namespace
metadata:
  name: device-manager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firmware-service-db-storage
  namespace: device-manager
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firmware-service-db
  namespace: device-manager
  labels:
    app: firmware-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firmware-service-db
  template:
    metadata:
      labels:
        app: firmware-service-db
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        command: ['redis-server', '--save', '60' '1']
        volumeMounts:
        - mountPath: /data
          name: firmware-service-db-storage
      volumes:
        - name: firmware-service-db-storage
          persistentVolumeClaim:
            claimName: firmware-service-db-storage
---
apiVersion: v1
kind: Service
metadata:
  name: firmware-service-db
  namespace: device-manager
  labels:
    app: firmware-service-db
spec:
  selector:
    app: firmware-service-db
  type: ClusterIP
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
