---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
- path: [metadata, annotations, volume.kubernetes.io/selected-node]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: PersistentVolumeClaim
      name: firmware-store
      namespace: device-manager
- path: [metadata, annotations, volume.kubernetes.io/storage-provisioner]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: PersistentVolumeClaim
      name: firmware-store
      namespace: device-manager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firmware-store
  namespace: device-manager
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firmware-service
  namespace: device-manager
  labels:
    app: firmware-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firmware-service
  template:
    metadata:
      labels:
        app: firmware-service
    spec:
      containers:
      - image: petewall/firmware-service
        name: firmware-service
        env:
          - name: PORT
            value: "5051"
          - name: FIRMWARE_STORE_TYPE
            value: filesystem
          - name: FILESYSTEM_FIRMWARE_STORE_PATH
            value: /var/data
        volumeMounts:
        - mountPath: "/var/data"
          name: firmware-store
      volumes:
        - name: firmware-store
          persistentVolumeClaim:
            claimName: firmware-store
---
apiVersion: v1
kind: Service
metadata:
  name: firmware-service
  namespace: device-manager
  labels:
    app: firmware-service
spec:
  type: ClusterIP
  selector:
    app: firmware-service
  ports:
  - port: 5051
    protocol: TCP
    targetPort: 5051
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firmware-service
  namespace: device-manager
  annotations:
    cert-manager.io/cluster-issuer: "cluster-ca-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
  - host: internal.petewall.net
    http:
      paths:
      - path: /devices/api/firmware
        pathType: Exact
        backend:
          service:
            name: firmware-service
            port:
              number: 5051
