---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firmware-store
  namespace: device-manager
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firmware-service
  namespace: device-manager
  labels:
    app: firmware-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firmware-service
  template:
    metadata:
      labels:
        app: firmware-service
    spec:
      containers:
      - image: petewall/firmware-service
        name: firmware-service
        env:
          - name: PORT
            value: "5051"
          - name: FIRMWARE_STORE_TYPE
            value: filesystem
          - name: FILESYSTEM_FIRMWARE_STORE_PATH
            value: /var/data
        volumeMounts:
        - mountPath: "/var/data"
          name: firmware-store
      volumes:
        - name: firmware-store
          persistentVolumeClaim:
            claimName: firmware-store
---
apiVersion: v1
kind: Service
metadata:
  name: firmware-service
  namespace: device-manager
  labels:
    app: firmware-service
spec:
  ports:
  - port: 5051
    protocol: TCP
    nodePort: 30051
    targetPort: 5051
  selector:
    app: firmware-service
  type: NodePort
