---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: device-manager-services
  namespace: device-manager
  annotations:
    cert-manager.io/cluster-issuer: "cluster-ca-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: public
  rules:
  - host: internal.petewall.net
    http:
      paths:
      - path: /device(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: device-manager
            port:
              number: 5050
      - path: /device/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: device-service
            port:
              number: 5051
      - path: /device/firmware(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: firmware-service
            port:
              number: 5052
      - path: /device/update(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ota-service
            port:
              number: 5053
