#@data/values
---
services:
- name: device-service
  repo:
      owner: petewall
      name: device-service
  branch: main
  image:
    repo: petewall/device-service
    tag: latest
- name: firmware-service
  repo:
      owner: petewall
      name: firmware-service
  branch: main
  image:
    repo: petewall/firmware-service
    tag: latest
- name: ota-service
  repo:
      owner: petewall
      name: ota-service
  branch: main
  image:
    repo: petewall/ota-service
    tag: latest
