resources:
- name: device-service
  type: registry-image
  icon: docker
  source:
    repository: petewall/device-service
    tag: latest
    username: ((dockerhub.username))
    password: ((dockerhub.password))
- name: firmware-service
  type: registry-image
  icon: docker
  source:
    repository: petewall/firmware-service
    tag: latest
    username: ((dockerhub.username))
    password: ((dockerhub.password))
- name: ota-service
  type: registry-image
  icon: docker
  source:
    repository: petewall/ota-service
    tag: latest
    username: ((dockerhub.username))
    password: ((dockerhub.password))
- name: device-service-source
  type: git
  icon: github
  source:
    uri: git@github.com:petewall/device-service.git
    branch: main
    private_key: ((github.private_key))
- name: firmware-service-source
  type: git
  icon: github
  source:
    uri: git@github.com:petewall/firmware-service.git
    branch: main
    private_key: ((github.private_key))
- name: ota-service-source
  type: git
  icon: github
  source:
    uri: git@github.com:petewall/ota-service.git
    branch: main
    private_key: ((github.private_key))
- name: golang
  icon: language-go
  type: registry-image
  source:
    repository: golang
    tag: 1.18-alpine
    username: ((dockerhub.username))
    password: ((dockerhub.password))
jobs:
- name: test-device-service
  plan:
  - in_parallel:
    - get: golang
    - get: source
      resource: device-service-source
      trigger: true
  - task: lint
    file: source/ci/tasks/test-lint.yaml
  - task: unit-tests
    image: golang
    file: source/ci/tasks/test-units.yaml
- name: test-firmware-service
  plan:
  - in_parallel:
    - get: golang
    - get: source
      resource: firmware-service-source
      trigger: true
  - task: lint
    file: source/ci/tasks/test-lint.yaml
  - task: unit-tests
    image: golang
    file: source/ci/tasks/test-units.yaml
- name: test-ota-service
  plan:
  - in_parallel:
    - get: golang
    - get: source
      resource: ota-service-source
      trigger: true
  - task: lint
    file: source/ci/tasks/test-lint.yaml
  - task: unit-tests
    image: golang
    file: source/ci/tasks/test-units.yaml
- name: build-device-service
  plan:
  - get: source
    resource: device-service-source
    trigger: true
    passed:
    - test-device-service
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
          username: ((dockerhub.username))
          password: ((dockerhub.password))
      inputs:
      - name: source
        path: .
      outputs:
      - name: image
      params:
        BUILD_ARG_GOOS: linux
        BUILD_ARG_GOARCH: amd64
        IMAGE_PLATFORM: linux/amd64
      run:
        path: build
  - put: device-service
    inputs:
    - image
    params:
      image: image/image.tar
- name: build-firmware-service
  plan:
  - get: source
    resource: firmware-service-source
    trigger: true
    passed:
    - test-firmware-service
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
          username: ((dockerhub.username))
          password: ((dockerhub.password))
      inputs:
      - name: source
        path: .
      outputs:
      - name: image
      params:
        BUILD_ARG_GOOS: linux
        BUILD_ARG_GOARCH: amd64
        IMAGE_PLATFORM: linux/amd64
      run:
        path: build
  - put: firmware-service
    inputs:
    - image
    params:
      image: image/image.tar
- name: build-ota-service
  plan:
  - get: source
    resource: ota-service-source
    trigger: true
    passed:
    - test-ota-service
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
          username: ((dockerhub.username))
          password: ((dockerhub.password))
      inputs:
      - name: source
        path: .
      outputs:
      - name: image
      params:
        BUILD_ARG_GOOS: linux
        BUILD_ARG_GOARCH: amd64
        IMAGE_PLATFORM: linux/amd64
      run:
        path: build
  - put: ota-service
    inputs:
    - image
    params:
      image: image/image.tar
